spring:

  config:
    import : optional:file:.env[.properties]
    
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true

server:
  port: 8081
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  issuer: cinetracks.com
